chemapi: "http://0.0.0.0:8066/ChemDUST"
modelseed:
    path: "/Users/fliu/workspace/jupyter/ModelSEEDDatabase"
cache: "/Users/fliu/workspace/jupyter/python3/annotation-server/data/"
neo4j:
    host: "0.0.0.0"
    port: 7687
    user: "neo4j"
    password: "123585"
redis:
    host: 'localhost'
    port: 6379
    db: 0
kbase:
    token: "4VW3677NZK7HX7Q3AHELGVVI55TMVDC5"
ortholog: true