chemapi: "http://172.18.0.5:8080/chemu"
modelseed:
    path: "/opt/data/ModelSEEDDatabase"
cache: "/opt/annotation/data/"
mongo_client: "mongodb+srv://server:dx75S3HBXX6h2U3D@bios-dk66o.gcp.mongodb.net/test?retryWrites=true&w=majority"
bios:
    host: ""
neo4j:
    host: "172.18.0.2"
    port: 7687
    user: "neo4j"
    password: "bioseed"
redis:
    host: '172.18.0.3'
    port: 6379
    db: 0
kbase:
    token: "B7DILTFRVH5ONJ5XSWG5XR2P5UBLAZKG"
ortholog: true
