chemapi: "http://172.18.0.4:8080/ChemDUST"
modelseed:
    path: "/opt/data/ModelSEEDDatabase"
cache: "/opt/annotation/data/"
mongo_client: "mongodb+srv://server:dx75S3HBXX6h2U3D@bios-dk66o.gcp.mongodb.net/test?retryWrites=true&w=majority"
neo4j:
    host: "172.18.0.2"
    port: 7687
    user: "neo4j"
    password: "123585"
redis:
    host: '172.18.0.3'
    port: 6379
    db: 0
kbase:
    token: "4VW3677NZK7HX7Q3AHELGVVI55TMVDC5"
ortholog: true